apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: python-app
spec:
  selector:
    name: app
    app: python-app
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000